name = "cf-image-hosting"
pages_build_output_dir = "./dist"
compatibility_date = "2024-05-12"
kv_namespaces = [
  { binding = "file_url", id = "kv_id"}
]

[env.production.vars]
API_HOST = "https://telegra.ph"
img_url = "file_url"

[env.production]
kv_namespaces = [
  { binding = "file_url", id = "kv_id"}
]